services:
  postgres:
    image: postgres:latest
    container_name: postgres_db2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ferico_test_db
    ports:
      - "5432:5432"
    restart: unless-stopped
